:docinfo:
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: googlecode
:toc: left
:sectlinks:
:linkattrs:
:hide-uri-scheme:

= API documentation of Rememberbrall
Eva Göttert

This artifact holds integration tests for Rememberbrall and generates living documentation from this program. In the next chapters, `de.rememberbrall.RememberbrallController` is being documented with its respective request and response semantics.

Additionally you can check out a Thymeleaf representation of all entries under link:/thymeleaf-entries[Rememberbrall Entries with Thymeleaf]

This documentation is done with https://github.com/rest-assured/rest-assured[Rest Assured] and http://projects.spring.io/spring-restdocs[Spring REST Docs].


== Get all entries

This endpoint provides all entries of Rememberbrall.

operation::get-all-entries[snippets='curl-request,http-request,http-response,response-fields']

== Get a specific entry

This endpoint gets a specific entry of Rememberbrall.

operation::get-specific-entry[snippets='curl-request,http-request,http-response,response-fields']

== Create an entry
This endpoint creates an entry to Rememberbrall.

operation::create-entry[snippets='curl-request,http-request,request-fields,http-response']

== Delete an entry

This endpoint deletes an entry from Rememberbrall.

=== Delete a non-existing entry

operation::delete-non-existing-entry[snippets='curl-request,http-request,http-response']

=== Delete a newly created entry

operation::delete-created-entry[snippets='curl-request,http-request,http-response']

== Delete all entries

operation::delete-all-entries[snippets='curl-request,http-request,http-response']

== Update an entry

operation::update-specific-entry[snippets='curl-request,request-fields,http-request,http-response']

